#!/usr/bin/expect -f
set timeout -1
proc slurp {file} {
    set fh [open $file r]
    set ret [read $fh]
    close $fh
    return $ret
}
set imageName [lindex $argv 0]

if {[string trimleft $imageName] eq ""} {
  puts "No Image file provided"
  exit
}

set cwd [file normalize [file dirname $argv0]]
set imagePath [file join $cwd $imageName]
puts $imageName
puts $imagePath\n

spawn docker run -it --rm -v $imagePath:/sdcard/filesystem.img lukechilds/dockerpi:vm

expect "raspberrypi login: "
send "pi\n"
expect "Password: "
send "raspberry\n"

expect "$ "
send "sudo apt-get update\n"
expect "$ "
send "sudo dpkg --configure -a\n"
expect "$ "
send "sudo apt-get -y purge wolfram-engine libreoffice* && sudo apt-get clean && sudo apt-get autoremove\n"
expect "$ "
send "sudo apt-get -y install dnsmasq pigpio python3-pigpio matchbox-keyboard lightdm git curl\n"
expect "$ "
send "sudo apt-get clean\n"
expect "$ "
send "sudo raspi-config --expand-rootfs\n"
expect "$ "
send "sudo raspi-config nonint do_i2c 0\n"
expect "$ "
send "sudo raspi-config nonint do_serial 0\n"
expect "$ "
send "sudo raspi-config nonint do_spi 0\n"
expect "$ "
send "sudo raspi-config nonint do_rgpio 0\n"
expect "$ "
send "sudo raspi-config nonint do_ssh 0\n"
expect "$ "
send "sudo raspi-config nonint do_vnc 0\n"
expect "$ "
send "sudo systemctl enable pigpiod\n"
expect "$ "
send "sudo systemctl start pigpiod\n"
expect "$ "
send "sudo raspi-config nonint do_boot_behaviour B2\n"
expect "$ "
send "sudo raspi-config nonint do_change_locale en_US.UTF-8\n"
expect "$ "
send "sudo raspi-config nonint do_configure_keyboard us\n"
expect "$ "
send "git clone https://github.com/joan2937/pigpio/\n"

set file [slurp "etc/dnsmasq.d/usb0"]
expect "# "
send "cat <<EOF >> /etc/dnsmasq.d/usb0\n"
send "$file\n"
send "EOF\n"

set file [slurp "etc/network/interfaces.d/usb0"]
expect "# "
send "cat <<EOF >> /etc/network/interfaces.d/usb0\n"
send "$file\n"
send "EOF\n"

set file [slurp "usr/local/sbin/usb-gadget.sh"]
expect "# "
send "cat <<EOF >> /usr/local/sbin/usb-gadget.sh\n"
send "$file\n"
send "EOF\n"
expect "# "
send "chmod +x /usr/local/sbin/usb-gadget.sh\n"

set file [slurp "lib/systemd/system/usbgadget.service"]
expect "# "
send "cat <<EOF >> /lib/systemd/system/usbgadget.service\n"
send "$file\n"
send "EOF\n"
expect "# "
send "systemctl enable usbgadget.service\n"

expect "# "
send "echo dtoverlay=dwc2 >> /boot/config.txt\n"

expect "# "
send "sed -i 's/$/ modules-load=dwc2/' /boot/cmdline.txt \n"

expect "# "
send "touch /boot/ssh\n"

expect "# "
send "echo libcomposite >> /etc/modules\n"

expect "# "
send "echo denyinterfaces usb0 >> /etc/dhcpcd.conf\n"

expect "# "
send "sudo systemctl enable getty@ttyGS0.service\n"

expect "# "
send "poweroff\n"

interact
